### ISSUE TITLE
Fatal Error in BeatSyncConsole: Error reading JToken from JsonReader

### ISSUE THREAD

**Issue by roobscoob** [Zingabopp/SyncSaberService#30]
Logs:
```[BeatSyncConsole - Info]: Starting BeatSyncConsole v0.8.1.0
[BeatSyncConsole - Info]: Running the latest release of BeatSyncConsole.
[BeatSyncConsole - Info]: configs\BeatSyncConsole.json not found, creating a new one.
[BeatSyncConsole - Info]: configs\BeatSync.json not found, creating a new one.
Would you like to replace the existing configs\BeatSync.json with a new one? (Y/N):
y
No song paths found in configs\BeatSyncConsole.json, should I search for game installs? (Y/N):
y
[BeatSyncConsole - Info]:   Steam: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber
[BeatSyncConsole - Info]: Found 1 game install, enabling for BeatSyncConsole: Steam: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber
[BeatSyncConsole - Info]: Using the following targets:
[BeatSyncConsole - Info]:   GameInstall: C:\Program Files (x86)\Steam\steamapps\common\Beat Saber
You have BeastSaber feeds enabled that require your bsaber.com username, enter your username:
*********
[BeatSyncLib - Warn]: History file not found at C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\UserData\BeatSyncHistory.json
[BeatSyncConsole - Info]: Hashing songs in 'C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_data\CustomLevels'...
[BeatSyncConsole - Error]: Fatal Error in BeatSyncConsole: Error reading JToken from JsonReader. Path '', line 1, position 1670.
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at BeatSyncLib.Utilities.Util.GenerateHash(String songDirectory, String existingHash) in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Utilities/Util.cs:line 182
   at BeatSyncLib.Hashing.SongHasher.<>c__DisplayClass18_0.<GetSongHashDataAsync>b__0() in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Hashing/SongHasher.cs:line 111
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at BeatSyncLib.Hashing.SongHasher.<>c__DisplayClass17_0.<<HashDirectoryAsync>b__1>d.MoveNext() in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Hashing/SongHasher.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at BeatSyncLib.Hashing.SongHasher.HashDirectoryAsync() in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Hashing/SongHasher.cs:line 95
   at BeatSyncConsole.Program.CreateJobBuilderAsync(Config config) in /_/BeatSyncConsole/Program.cs:line 87
   at BeatSyncConsole.Program.Main(String[] args) in /_/BeatSyncConsole/Program.cs:line 200
Stopping LogManager.
Press Enter to continue...```

**Comment by Zingabopp** [comment]
Wrong repository, but will be fixed in next version. <https://github.com/Zingabopp/BeatSync/actions/runs/181411866>
