### ISSUE TITLE
Fails to download zips

### ISSUE THREAD

**Issue by scavezze** [Zingabopp/SyncSaberService#5]
[Program.cs_Main(110) @ 23:27 - Info] Exception downloading BeastSaberFeed (2) - System.AggregateException-One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SyncSaberService.SyncSaber.DownloadSongs(Dictionary`2 queuedSongs)
   at SyncSaberService.SyncSaber.DownloadSongsFromFeed(String feedType, IFeedSettings _settings)
   at SyncSaberService.Program.Main(String[] args)

Temp directory has 1KB corrupted zips so everything fails

**Comment by AngusB42** [comment]
Also getting this error.

[SyncSaberService @ 04:02 - Info] Playlist "SyncSaber Playlist" found in old playlist format.
[SyncSaberService @ 04:02 - Info] Playlist "BeatSaver Newest" found in old playlist format.
[SyncSaberService @ 04:02 - Info] Playlist "BeastSaber Curator Recommended" found in old playlist format.
[SyncSaberService @ 04:02 - Info] Playlist "BeastSaber Followings" found in old playlist format.
[SyncSaberService @ 04:02 - Info] Playlist "BeastSaber Bookmarks" found in old playlist format.
[SyncSaberService @ 04:02 - Info] Playlist "ScoreSaber Top PP" found in old playlist format.

[SyncSaberService @ 04:02 - Warning] Skipping FavoriteMappers.ini feed, no authors found in C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\UserData\FavoriteMappers.ini

[SyncSaberService @ 04:02 - Info] Downloading songs from bookmarks feed...
[SyncSaberService @ 04:02 - Info] Finished checking pages, found 43 songs
[Program.cs_Main(142) @ 04:02 - Info] Exception downloading BeastSaberFeed (1) - System.AggregateException-One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SyncSaberService.SyncSaber.DownloadSongs(Dictionary`2 queuedSongs)
   at SyncSaberService.SyncSaber.DownloadSongsFromFeed(String feedType, IFeedSettings _settings)
   at SyncSaberService.Program.Main(String[] args)

[SyncSaberService @ 04:02 - Info] Finished downloading songs in 0 min 1 sec

**Comment by Zingabopp** [comment]
This is due to BeatSaver's new song ID format (single hex number instead of 1234-1234). An update should be coming sometime this week to fix it.

**Comment by Zingabopp** [comment]
Fixed in 0.1.0
